### ISSUE TITLE
blog案例展示

### ISSUE THREAD

**Issue by the5fire** [the5fire/django_selfblog#2]
用这套源码搭建起来博客的同学不妨放着链接在这里。也方便大家参观。也可以带些流量。

跟帖格式可以如下，按照我的博客来说。

blog：http://the5fire.com
服务器：webfaction centos
部署环境：virtualenv+supervisord+nginx+django1.5

**Comment by aidenzou** [comment]
blog: http://www.webdevs.cn
服务器：aliyun
部署环境：nginx+ php + yii2 + mysql

**Comment by the5fire** [comment]
@aidenzou php是什么鬼？

**Comment by ghacer** [comment]
blog：http://shuadadao.info
vps：DO  Centos
nginx + supervisor + virtualenv + gunicorn +  django1.8
借鉴（抄袭）很多， 感激（爽得）不尽。

**Comment by TianBright** [comment]
@the5fire , 我搭建遇到问题，请教：
已安装虚拟环境和依赖包，数据库已设置完毕，在执行python manage.py syncdb的时候，报错：

(nbenv)[root@StabilityPython selfblog]# python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nbenv/lib/python2.6/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/nbenv/lib/python2.6/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nbenv/lib/python2.6/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/nbenv/lib/python2.6/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/home/nbenv/lib/python2.6/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/home/nbenv/lib/python2.6/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/home/nbenv/lib/python2.6/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/home/nbenv/lib/python2.6/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/home/nbenv/lib/python2.6/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named duoshuo

请问这个怎么解决？

**Comment by CharmingZhou** [comment]
blog: http://charmingzhou.com

服务器： 阿里云 centos

部署环境： virtualenv+nginx+gunicorn+django1.7

**Comment by the5fire** [comment]
@TianBright 需要安装duoshuo的模块
